import random
import string
x = input("Would you like your person to be male or female: ")
if x == ("male"):
    hair1 = ['Brown', 'Ginger', 'Blonde', 'Dirty Blonde', 'Black']
    hair2 = ['Brown', 'Ginger', 'Blonde', 'Dirty Blonde', 'Black']
    h1 = random.choice(hair1)
    h2 = random.choice(hair2)
    race1 = ['Asian', 'White', 'Black', 'Hispanic', 'Latino', 'Germanic']
    race2 = ['Asian', 'White', 'Black', 'Hispanic', 'Latino', 'Germanic']
    height1 = ['5`2', '5`3', '5`4', '5`5', '5`6', '5`7', '5`8', '5`9', '5`10', '5`11', '6`0']
    height2 = ['5`2', '5`3', '5`4' '5`5', '5`6', '5`7', '5`8', '5`9', '5`10', '5`11', '6`0']
    he1 = random.choice(height1)
    he2 = random.choice(height2)

    r1 = random.choice(race1)
    r2 = random.choice(race2)
    c = random.randint(4, 10)
    e = random.randint(4, 10)
    g1 = random.randint(9, 12)
    g2 = random.randint(9, 12)
    d = random.randint(4, 10)
    a = random.randint(4, 10)
    b = random.randint(4, 10)
    f = random.randint(4, 10)
    h = random.randint(4, 10)
    i = random.randint(4, 10)
    j = random.randint(4, 10)
    k = random.randint(4, 10)
    l = random.randint(4, 10)
    m = random.randint(4, 10)
    n = random.randint(4, 10)
    o = random.randint(4, 10)
    print("Guy 1")
    print("Hair: ", h1)
    print("Race: ", r2)
    print("Height: ", he1)
    print("Grade: ", g1)
    print("Body: ", b)
    print("Face: ", c)
    print("Personality: ", d)
    print("Similarities: ", e)
    print("Smartness: ", f)
    print("Athletics: ", n)
    print()
    print("Guy 2")
    print("Hair: ", h2)
    print("Race: ", r1)
    print("Height: ", he2)
    print("Grade: ", g2)
    print("Body: ", i)
    print("Face: ", j)
    print("Personality: ", k)
    print("Similarities: ", l)
    print("Smartness: ", m)
    print("Athletics: ", o)
else:
    hair1 = ['Brown', 'Ginger', 'Blonde', 'Dirty Blonde', 'Black']
    hair2 = ['Brown', 'Ginger', 'Blonde', 'Dirty Blonde', 'Black']
    h1 = random.choice(hair1)
    h2 = random.choice(hair2)
    race1 = ['Asian', 'White', 'Black', 'Hispanic', 'Latino', 'Germanic']
    race2 = ['Asian', 'White', 'Black', 'Hispanic', 'Latino', 'Germanic']
    r1 = random.choice(race1)
    r2 = random.choice(race2)
    height1 = ['5`2', '5`3', '5`4' '5`5', '5`6', '5`7', '5`8', '5`9', '5`10', '5`11', '6`0']
    height2 = ['5`2', '5`3', '5`4' '5`5', '5`6', '5`7', '5`8', '5`9', '5`10', '5`11', '6`0']
    he1 = random.choice(height1)
    he2 = random.choice(height2)

    c = random.randint(4, 10)
    e = random.randint(4, 10)
    g1 = random.randint(9, 12)
    g2 = random.randint(9, 12)
    d = random.randint(4, 10)
    a = random.randint(4, 10)
    b = random.randint(4, 10)
    f = random.randint(4, 10)
    h = random.randint(4, 10)
    i = random.randint(4, 10)
    j = random.randint(4, 10)
    k = random.randint(4, 10)
    l = random.randint(4, 10)
    m = random.randint(4, 10)
    n = random.randint(4, 10)
    o = random.randint(4, 10)
    print("Girl 1")
    print("Hair: ", h1)
    print("Race: ", r2)
    print("Height: ", he1)
    print("Grade: ", g1)
    print("Body: ", a)
    print("Face: ", c)
    print("Personality: ", d)
    print("Similarities: ", e)
    print("Smartness: ", f)
    print("Athletics: ", o)
    print()
    print("Girl 2")
    print("Hair: ", h2)
    print("Race: ", r1)
    print("Height: ", he2)
    print("Grade: ", g2)
    print("Body: ", o)
    print("Face: ", j)
    print("Personality: ", k)
    print("Similarities: ", l)
    print("Smartness: ", m)
    print("Athletics: ", n)


